{% set name = "metaimageio" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fddd289c1c18326b3fabf678688c973f12fde4134fd9efcda28b167e68a4c342

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
  run:
    - numpy >=1.26
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - metaimageio

about:
  home: https://auneri.github.io/MetaImageIO
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Support for reading and writing images in MetaIO file format

extra:
  recipe-maintainers:
    - auneri
