{% set name = "metaimageio" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c37bde5bd482ebe73e9e16123a7d88107c09748ff79fa4a6f40e933803aa8404

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
  run:
    - numpy >=1.26
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - metaimageio

about:
  home: https://auneri.github.io/MetaImageIO
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Support for reading and writing images in MetaIO file format

extra:
  recipe-maintainers:
    - auneri
