{% set name = "metaimageio" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 935c1aaba2b222518a09996cfa306defa8240e55639cc92140fb95c8e36f30ec

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - imageio >=2.8
    - numpy >=1.19
    - python >=3.6

test:
  imports:
    - metaimageio

about:
  home: https://auneri.github.io/MetaImageIO
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Support for reading and writing images in MetaIO file format

extra:
  recipe-maintainers:
    - auneri
